# Generated by Django 3.2.12 on 2022-04-20 18:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a make (pl. Ford):', max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('mileage', models.PositiveIntegerField()),
                ('comments', models.CharField(blank=True, max_length=500)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make')),
            ],
        ),
    ]
